# pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/grafana"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: kubernetes-dashboard
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: "manual"
  volumeName: grafana
